### PR TITLE
haddock-api 2.21.0 and haddock-library 1.6.1 release

### PR DESCRIPTION
**Pull request by harpocrates**
Updates `.cabal` files,`CHANGELOG's, README, and Travis CI.

Also accepted an incorrectly failing test case.

### CODE REVIEW

**Comment by peti** [comment]
Will the new version support ghc-8.6.1? It would be great to get that release soon because currently haddock-library blocks all kinds of dependent packages, like pandoc, from building with the latest compiler.

**Comment by harpocrates** [comment]
> Will the new version support ghc-8.6.1? It would be great to get that release soon because currently haddock-library blocks all kinds of dependent packages, like pandoc, from building with the latest compiler.

Yes, it will support ghc-8.6. The release should be coming soon.

**Comment by peti** [comment]
Ping?

**Comment by alexbiehl** [comment]
Ben, I am travelling for some time. Herbert and Alec are in charge here.
But I guess nothing is stopping here, right @hvr, @harpocrates?

Ben Gamari <notifications@github.com> schrieb am Do., 11. Okt. 2018, 14:23:

**Comment by harpocrates** [comment]
This is ready.

I don't have the permissions to release to Hackage. I've been pinging Herbert regularly, but I think he's been busy with other things. The plan is to merge this right before publishing on Hackage.

**Pull request merged**
