### PR TITLE
Port HTML backend to Lucid

### PR DESCRIPTION
**Pull request by AriFordsham**
Haddock generates HTML using xhtml, which is both [unmaintained](https://github.com/haskell/xhtml/issues/16#issuecomment-1344544478) and [slow](https://www.parsonsmatt.org/2022/12/21/haddock_performance.html).

This ports to Lucid, which is a maintained, performance-oriented replacement. 

Lucid (transitively) contains one out-of-boot dependency, blaze-markup, but will allow removal of xhtml from boot (assuming Haddock is the only user of boot xhtml?). This increases the total number of boot libraries by one, but allows removing an unmaintained one.

I assume there's some process to go through to get the change in boot libraries to happen.

According to the test suite it seems to be correct, but may be missing further testing, and has not been benchmarked.

Still to be done:
- [x] Carefully compare new and old outputs to check correctness
- [ ] Benchmark to ascertain performance benefit
- [ ] Clean up PR
- [ ] Work out getting neccesary ghc-boot changes approved

### CODE REVIEW

**Comment by AriFordsham** [comment]
As far as I can see, the output now of the golden tests now matches the originals.

**Comment by AriFordsham** [comment]
Didn't realise @parsonsmatt was already on to this: https://github.com/haskell/haddock/pull/1561. Should this be closed?

**Comment by FinleyMcIlwaine** [comment]
@AriFordsham I don't think this patch is worth pursuing further, for the time being. Adding lucid as a boot library, and transitively blaze-markup, would require a disproportionate amount of maintenance overhead for the potential improvements (based on those reported in the [existing patch](https://github.com/haskell/haddock/pull/1561#issue-1513292314)). A simpler and more incremental win appears to be optimizing xhtml directly, and I think that's the way to go for now.

**Comment by Kleidukos** [comment]
I'd like to approach this again after GHC 9.8 is release, which will mark the return of Haddock in the GHC tree. Indeed while the question of dependencies is critical, `lucid2` is dropping the non-boot dependency on `blaze-builder` https://github.com/chrisdone/lucid/issues/143.

This will allow us to add lucid2 as a dependency and remove `xhtml` from GHC's boot dependencies.

**Comment by Kleidukos** [comment]
@AriFordsham Thanks for starting this btw, I'm closing this PR but the effort will continue on the Haskell GitLab once Haddock moves there. :)

**Comment by AriFordsham** [comment]
@Kleidukos bumping this PR, as Haddock is now in GHC and Lucid's `blaze-builder` dependency is gone. I unfortunately don't have the time for this anymore, but I wanted to bring it back to your attention.

**Pull request closed without merging**
