### PR TITLE
Follow changes in GHC build system

### PR DESCRIPTION
**Pull request by thomie**
Please merge with ghc-head. I'm doing some refactoring of the GHC build system.

### CODE REVIEW

**Comment by Fuuzetsu** [comment]
@thomie I wonder if you could properly set up haddock-library haddock-api and haddock packages in the build system then. If you look at the top-level haddock file, we currently have a flag which is effectively a hack for GHC build system: when we're in GHC tree, we pretend there are no packages and that it's all just one source tree, which is not great.

Will merge this in a few.

**Comment by thomie** [comment]
Making that change would probably mean that haddock-api and haddock-library will be installed in the global package database. Would that a problem in any way?

**Comment by hvr** [comment]
@thomie that'd be undesirable IMHO

**Comment by thomie** [comment]
Why?

**Pull request merged**
