### PR TITLE
Add a flag to hide instance lists

### PR DESCRIPTION
**Pull request by Lysxia**
See #698 

Is this the right way to add such a flag? That seems like a lot of lines to touch.

### CODE REVIEW

**Comment by harpocrates** [comment]
> Is this the right way to add such a flag? That seems like a lot of lines to touch.

I think this is the right way. I agree that the line diff is unfortunate. One refactor that will be in order (as soon as some of the other larger architectural changes are done) is to package together a bunch of the parameters that get threaded through everywhere (qual options, whether to use unicode, etc.) into one record.

Then, adding a flag like this one would be a matter of extending that record.

**Comment by harpocrates** [comment]
I'm curious, what does this bring us that we don't already get with https://github.com/haskell/haddock/pull/995? Is it just whether instance lists are open or closed by default? If so, I'm a bit wary of

  * introducing yet another command line flag
  * how invasive the line change (esp. for such a relatively small functionality change)

Also, won't https://github.com/haskell/haddock/pull/1007 (once it is no longer WIP) render this obsolete?

**Comment by Lysxia** [comment]
Indeed, the feature overlap is quite perplexing. The main point of this PR (compared to the other(s)) is to have instances folded statically, without relying on Javascript which may happen to be either unavailable or simply slow, nor on any pre-setting on the part of visitors (#1007 still requires a few clicks).

As the various examples from the mailing list discussion (linked in #698) show, there are some modules where instances have no business starting out unfolded, so it seems fair to be able to fix that statically.

For these reasons, I still consider this PR to be the main solution to issue #698.

About your point on line changes, do you have an idea of when the refactoring of options would be appropriate you mentioned earlier would be appropriate to do?

**Comment by Lysxia** [comment]
In the end this feature might be too niche to be worth it. cc @Kleidukos

**Pull request closed without merging**
