### PR TITLE
Hide instances by default

### LINKED ISSUE #698: Hide instances by default
Even browsing through the Prelude is a hassle, among many other examples, because of the hundreds of instances that come with each type class.

### PR DESCRIPTION
**Pull request by Lysxia**
Fixes #698.

### CODE REVIEW

**Comment by sjakobi** [comment]
I would like to have this.

@alexbiehl: Can this get merged?

**Comment by Lysxia** [comment]
Ping @harpocrates. This is ready for review.

**Comment by harpocrates** [comment]
@Lysxia Thanks for rebasing! I haven't merged this sooner because I'm a bit wary of pushing through stylistic changes which aren't obvious improvements (especially after the new theme). In other words: it isn't clear to me that this is a change that most people will want. If you could encourage folks to give feedback either in a mailing list, on IRC, on Reddit, or simply as 👍/👎 on the PR, I'll happily merge.

Personally, I'm neither a 👍 nor a 👎.

Again, I'm really sorry for letting this live in a limbo state for so long. 😞

**Comment by Lysxia** [comment]
I see, that makes sense. I'll start a thread on haskell-café to get feedback.

**Comment by ntc2** [comment]
**I'm an enthusiastic :+1: on collapsing instances by default.**

**For example, the `Prelude` Haddocks are 98 screens tall with instances expanded [1], vs 40 screens with instances collapsed [2].** I.e. the `Prelude` documentation is 60% instances! When looking at documentation I usually don't care about the instances until I've zeroed in on a specific data type. Similar with examples, where I'm happy they are collapsed by default.

[1] prelude-expanded-98-screens
[2] prelude-collapsed-40-screens

**Comment by david-christiansen** [comment]
It seems to me that this might make it more difficult to find information by searching in the page, given that Ctrl-F will typically skip hidden content. In the past, I've used Ctrl-F to get an overview of instances and datatypes when trying to figure out a library.

What about adding an "expand all" button, to continue supporting this use case?

**Comment by Lysxia** [comment]
Thanks everyone for the feedback! After more thinking and discussion on Haskell-café, it seems too radical to switch the default globally. Or at the very least, more experimentation is necessary. So I will close this PR for now and continue discussion on #698.

**Pull request closed without merging**
