### PR TITLE
Fix after binder collect changes

### PR DESCRIPTION
**Pull request by hsyl20**
PR for https://gitlab.haskell.org/ghc/ghc/-/merge_requests/4464

### CODE REVIEW

**Review by alexbiehl-gc — APPROVED** [review]

**Comment by Kleidukos** [comment]
Let's go :rocket:

**Comment by alexbiehl-gc** [comment]
Oh wait, that might have been too early, the corresponding MR on Gitlab has not been merged yet. Maybe we introduce a new Github label to signal "please wait for the linked MR has been merged".

**Comment by Kleidukos** [comment]
@alexbiehl-gc According to @hsyl20, this PR was required to be merged before !4464 was to be merged (I imagine he will then update the submodule on GHC's side, which will make his MR mergeable)

**Comment by hsyl20** [comment]
Yes I'm currently rebasing to use the merge commit of this PR in the GHC MR

**Comment by alexbiehl-gc** [comment]
Ok, glad to hear. @hsyl20 Note that you might need to adjust the perf metrics as your bump implies https://gitlab.haskell.org/ghc/ghc/-/merge_requests/4687 

Happy to have someone push it through finally

**Comment by hsyl20** [comment]
Oh we should have https://gitlab.haskell.org/ghc/ghc/-/merge_requests/4687 merged first.

**Comment by alexbiehl-gc** [comment]
Oh, ok. Can you maybe assign Marge? I fear there are several Haddock bumps racing for merge right now and the review/marging is really a bottleneck.

**Comment by Kleidukos** [comment]
I have approved !4687 and assigned Marge.

**Comment by alexbiehl-gc** [comment]
Thanks!

**Pull request merged**
