### PR TITLE
The Haddock part for fully gcc-like response files

### PR DESCRIPTION
**Pull request by randen**
This is intended to fix haskell/haddock#379. The other half is haskell/cabal#3004, which is not actually complete without the version number of haddock which will support this style of response file.

### CODE REVIEW

**Comment by 23Skidoo** [comment]
The first two commit look unrelated, I think you need to rebase this against `master`.

**Comment by randen** [comment]
close in favor of a cleaner pull request

**Comment by 23Skidoo** [comment]
You can just do `push -f` to destructively update this PR.

**Comment by randen** [comment]
To complete the story for archeologists (including myself--I wasn't able to find it immediately), I should have linked the PR that was used: #470

**Pull request closed without merging**
