### PR TITLE
Update Travis configuration for containers

### PR DESCRIPTION
**Pull request by bgamari**
This should speed up builds. See
https://github.com/hvr/multi-ghc-travis/blob/master/README.md#travisyml-for-container-based-infrastructure

### CODE REVIEW

**Comment by Fuuzetsu** [comment]
```
Disallowing packages: ghc-7.10.2

If you require these packages, please review the package approval process at: https://github.com/travis-ci/apt-package-whitelist#package-approval-process
```

We currently can't use it because while hvr's ppa is whitelisted, the ghc-7.10.2 package is not.

**Comment by Fuuzetsu** [comment]
https://github.com/travis-ci/apt-package-whitelist/issues/927

**Comment by glguy** [comment]
GHC 7.10.2 is whitelisted on Travis-CI now. Perhaps this can move forward now.

**Comment by Fuuzetsu** [comment]
Yes, I plan to when time allows

**Pull request merged**
