### PR TITLE
Use functions exported from GHC.HsToCore.Docs

### PR DESCRIPTION
**Pull request by wz1000**
See https://gitlab.haskell.org/ghc/ghc/-/merge_requests/3475

This seems like low hanging fruit from https://github.com/haskell/haddock/pull/906 that should be easy to adopt, and a clear win since it reduces duplication and synchronization bugs like https://gitlab.haskell.org/ghc/ghc/issues/18241.

/cc @sjakobi

### CODE REVIEW

**Comment by wz1000** [comment]
@harpocrates thoughts on this?

**Comment by sjakobi** [comment]
Thanks @wz1000! This looks like a nice improvement to me. :)

**Comment by harpocrates** [comment]
Yes, thank you! Did you make sure the deleted code really matches the Haddock one (in other words - has there been any accidental divergence?). If so, LGTM. 👍

**Comment by wz1000** [comment]
I had quickly gone through it earlier, but I just went through it line by line. I found one missing case, one missing bang pattern and one missing comment. I've updated the ghc MR with these now.

**Comment by harpocrates** [comment]
Thanks! That’s my only concern so, all good on the Haddock side - merge with the GHC MR I guess.

**Pull request merged**
