### PR TITLE
Correctly handle Backpack identity/semantic modules.

### PR DESCRIPTION
**Pull request by ezyang**

### CODE REVIEW

**Comment by alexbiehl** [comment]
@ezyang Whats the status of this? I noticed you also include 9acb289 is this necessary? haddock/master is currently on ghc-8.2 only.

**Comment by ezyang** [comment]
I merged this to ghc-head, I guess it needs to be merged to master as well.

**Comment by alexbiehl** [comment]
Thanks @ezyang. I can take care of merging into master if you want.

**Comment by ezyang** [comment]
That would be great, thank you.

**Comment by alexbiehl** [comment]
Ah, the relevant part has already been merged with https://github.com/haskell/haddock/commit/68e531baa35e698d947686b83525871eb33c3730. Closing this.

**Pull request closed without merging**
