### PR TITLE
 extractDecl: Correctly extract associated types 

### LINKED ISSUE #735: GHC 8.4.1-alpha panic (extractDecl)
I originally observed this in [this Travis build](https://travis-ci.org/ekmett/ad/jobs/328314307#L1535). Here is a minimal way to reproduce the issue:

```haskell
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE TypeFamilies #-}
module Bug (Scalar) where

class (Num (Scalar t)) => Mode t where
  type Scalar t
```

In `haddock-2.18.1` (the Haddock bundled with GHC 8.2.2), this works fine:

```
$ /opt/ghc/8.2.2/bin/haddock Bug.hs --html
Haddock coverage:
   0% (  0 /  1) in 'Bug'
  Missing documentation for:
    Module header
```

However, in `haddock-2.18.2` (the Haddock bundled with GHC 8.4.1-alpha), this panics:

```
$ /opt/ghc/8.4.1/bin/haddock Bug.hs --html
Haddock coverage:
haddock: panic! (the 'impossible' happened)
  (GHC version 8.4.0.20171222 for x86_64-unknown-linux):
        extractDecl

Ambiguous decl for Scalar in class:
    class (Num (Scalar t)) => Mode t where
      type Scalar t
      {-# MINIMAL #-}
Matches:
    []
Call stack:
    CallStack (from HasCallStack):
      callStackDoc, called at compiler/utils/Outputable.hs:1150:37 in ghc:Outputable
      pprPanic, called at utils/haddock/haddock-api/src/Haddock/Interface/Create.hs:1013:16 in main:Haddock.Interface.Create
```

### PR DESCRIPTION
**Pull request by alexbiehl**
(fixes #735)

Generating documentation for
```haskell
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE TypeFamilies #-}
module Bug (Scalar) where

class (Num (Scalar t)) => Mode t where
  type Scalar t
```
Results in 

image

- [x] Do we expect a "class context" here to signify that this is an associated type? What would it look like?
- [ ] Add a test
- [ ] Merge to `ghc-head` branch

### CODE REVIEW

**Comment by RyanGlScott** [comment]
This looks great!

To answer the question in the first bullet point: no, I don't have a strong opinion about whether we should print anything about the surrounding class. Inside of GHC, associated type families are desugared into top-level type families, so it's not technically inaccurate to present one independently of its surrounding class.

Moreover, since this is a scenario where we're specifically exporting the associated type family but _not_ the surrounding class, perhaps it's better to simply not mention the surround class at all in the Haddocks.

**Comment by alexbiehl** [comment]
Alright thanks for the feedback!

**Comment by gbaz** [comment]
Does this get things any closer on https://github.com/haskell/haddock/issues/526 and https://github.com/haskell/haddock/issues/664 ?

**Comment by alexbiehl** [comment]
Yes.

gbaz <notifications@github.com> schrieb am Mo., 5. Feb. 2018, 08:54:

**Pull request merged**
