### PR TITLE
Expand user-collapsible sections (#699)

### PR DESCRIPTION
**Pull request by Lysxia**
See #699 for discussion.

### CODE REVIEW

**Comment by alexbiehl** [comment]
Nice, thank you. I think you have to update the tests to make Travis happy.

**Comment by hvr** [comment]
Tbh, we made them collapsed by default *because* they would clutter everything. If they're expanded by default what's the point of having anything collapsible?

**Comment by Lysxia** [comment]
@hvr That makes sense. I didn't think this through. I'll think of another way to make these sections more visible...

**Comment by ntc2** [comment]
@Lysxia I'm excited about your #700 , but this PR seems to do the opposite for examples, and I agree with @hvr that it's a bad idea. However, I think adding a button that toggles visibility of all of the examples (but not the instances) could be useful, while leaving the examples collapsed by default.

**Comment by Lysxia** [comment]
@ntc2 Thanks! That sounds like a better idea.

**Pull request closed without merging**
