### PR TITLE
Bump ghc-head

### PR DESCRIPTION
**Pull request by hsyl20**
Add the commit for https://gitlab.haskell.org/ghc/ghc/-/merge_requests/7175

It seems the branch is out of sync again so there are 2 additional unrelated commits

### CODE REVIEW

**Review by Kleidukos — APPROVED** [review]
LGTM

**Comment by Ericson2314** [comment]
FYI this was squash-merged which instead of getting the repos back in sync, made the history (if not state of the code itself) diverge more!

**Comment by Kleidukos** [comment]
@Ericson2314 Yes, this kind of unfortunate occurrence is why the development of ghc-head has no moved to the Gitlab fork of Haddock.

**Comment by Ericson2314** [comment]
Yeah looking forward to @wz1000's work so there is much less coupling.

**Pull request merged**
