### PR TITLE
Clean up unused imports

### PR DESCRIPTION
**Pull request by nineonine**
I was building ghc and noticed a few unused import warnings.

### CODE REVIEW

**Comment by nineonine** [comment]
@bgamari

**Comment by nineonine** [comment]
also this
```
utils/haddock/haddock-api/src/Haddock/GhcUtils.hs:119:1: warning: [-Wincomplete-patterns]
    Pattern match(es) are non-exhaustive
    In an equation for ‘hsTyVarBndrName’:
        Patterns not matched: XTyVarBndr _
    |
119 | hsTyVarBndrName (UserTyVar _ _ name) = unXRec @n name
```

**Comment by Kleidukos** [comment]
Is this patch specific to GHC's integration of Haddock or can it be merged in the normal branches as well?

**Comment by nineonine** [comment]
I am not 100% sure but I opened PR against `haskell:ghc-head` so must be the former?

**Comment by Kleidukos** [comment]
As per the [CONTRIBUTING](https://github.com/haskell/haddock/blob/ghc-9.2/CONTRIBUTING.md#git-branches) document:

> If your patch consists of glue code and interface changes with GHC, please open a Pull Request targeting the ghc-head branch.

> Otherwise, for improvements to the documentation generator, please base your pull request on the current GHC version branch (ghc-9.0 for instance). The PR will be forward-ported to ghc-head so that documentation built within GHC can benefit from it.

I'll let you re-target the PR to the proper branch (9.2 as of today. :)

**Comment by Kleidukos** [comment]
Hi!  As of today, patches for the `ghc-head` branch must be done on the Haddock mirror on GitLab, at https://gitlab.haskell.org/ghc/haddock.

**Pull request closed without merging**
