### PR TITLE
Docs for some of DocH's less intuitive constructors

### PR DESCRIPTION
**Pull request by sjakobi**

### CODE REVIEW

**Comment by alexbiehl** [comment]
Thanks Simon! I don't mind if you push directly to master for small changes like these.

**Comment by sjakobi** [comment]
> Thanks Simon! I don't mind if you push directly to master for small changes like these.

Will do. To `master` or to `ghc-8.4` though?

(If `master` currently has no use, I'd propose deleting it to reduce confusion.)

**Comment by alexbiehl** [comment]
Ah right. Let's delete master.

**Comment by sjakobi** [comment]
Can you remove the branch protection on `master`?

**Comment by sjakobi** [comment]
Gosh, sorry for the mess with the pull requests. I can clean this up by retargeting to the ghc-8.4 branch.

**Comment by sjakobi** [comment]
The affected PRs are #670, #729, #721, #728, #708, #562, #700 and #692.

**Comment by ntc2** [comment]
@sjakobi , @alexbiehl : looks like all of the PRs mentioned in [@sjakobi 's last comment](https://github.com/haskell/haddock/pull/814#issuecomment-387692741) just got closed, but it's unclear why. Could someone explain what's going on?

**Comment by sjakobi** [comment]
@ntc2: The master branch was deleted as it didn't have a clear function in this repo. What @alexbiehl and I hadn't considered, was that GitHub would close all PRs targeting the master branch.

To reopen an affected PR, you can try changing the merge target to the ghc-8.4 branch by clicking the `Edit` button to the right of the PR's title. Some PRs may have to be rebased.

**Comment by sjakobi** [comment]
Thanks for helping out with this mishap, @ntc2! As #700 seems to show, simply retargeting the PR doesn't appear to work. :/

Hopefully rebasing will work for the affected PRs. As a last resort, submitters can open a new one. :/

**Pull request merged**
