### PR TITLE
Update ghc-head

### PR DESCRIPTION
**Pull request by sjakobi**
I have cherry-picked everything from ghc-8.4 onto ghc-head but haven't taken care of the tests so far.

In addition, 5193e44 is a small adjustment for DerivingVia.

Using c7bc067, I get [this test output](https://github.com/haskell/haddock/files/2088120/test.log).

Apart from html-test the testsuites pass, although there are warnings that I hadn't seen before:

```
No HTML directory found for base test dependency: array
No HTML directory found for base test dependency: base
No HTML directory found for base test dependency: ghc-prim
No HTML directory found for base test dependency: process
No HTML directory found for base test dependency: template-haskell
```

Can someone familiar with the recent changes please look at the diffs for html-test and figure out if there are any problems?

### CODE REVIEW

**Comment by alexbiehl** [comment]
@sjakobi Thanks for your work. I will take a look at the tests.

**Comment by alexbiehl** [comment]
I think the output you get with c7bc067 is legit. It just means that now you are able to link stuff which you couldn't before.

**Comment by harpocrates** [comment]
> Apart from html-test the testsuites pass, although there are warnings that I hadn't seen before:
>
> ```
> No HTML directory found for base test dependency: array
> No HTML directory found for base test dependency: base
> No HTML directory found for base test dependency: ghc-prim
> No HTML directory found for base test dependency: process
> No HTML directory found for base test dependency: template-haskell
> ```

That's new from c7bc06743bcb9e88cd05edfae4b7269a8015adce.

**Comment by sjakobi** [comment]
@alexbiehl:

> I think the output you get with c7bc067 is legit.

So I can simply accept the new output!?

**Comment by alexbiehl** [comment]
> So I can simply accept the new output!?
Yes.

**Comment by sjakobi** [comment]
In order to incorporate @hvr's `wip/ghc-head` in this update I tried to rebase `ghc-8.4` on `wip/ghc-head`.

When building that branch I ran into the following error:

```
src/Haddock/Types.hs:678:15: error:
    Not in scope: type constructor or class ‘XPArrTy’
    Perhaps you meant ‘XParTy’ (imported from GHC)
    |
678 | type instance XPArrTy          DocNameI = NoExt
```

I haven't looked into this further.

**Comment by harpocrates** [comment]
Parallel arrays were recently removed (see f77c9c5cc8bb669f584d36494630589ea80eb799), so that instance no longer makes sense.

**Comment by sjakobi** [comment]
> Parallel arrays were recently removed (see f77c9c5), so that instance no longer makes sense.

Ah thanks. I forgot to include the recent changes on `ghc-head`.

**Comment by sjakobi** [comment]
Closed in favor of #857.

**Pull request closed without merging**
