### PR TITLE
Accumulate explicitly which modules to load for 'attachInstances'

### PR DESCRIPTION
**Pull request by harpocrates**
The old approach to fixing #469, while correct, consumes a lot of
memory. We ended up with a HUGE `GblRdrEnv` in `ic_rn_gbl_env`. However,
`getNameToInstancesIndex` takes that environment and compresses it down
to a much smaller `ModuleSet`.

Now, we compute that `ModuleSet` explicitly as we process modules. That
way we can just tell `getNameToInstancesIndex` what modules to load
(instead of it trying to compute that information from the interactive
context).

### CODE REVIEW

**Comment by harpocrates** [comment]
Relevant issue: #462.

This won't build without GHC side changes to `getNameToInstancesIndex`: https://phabricator.haskell.org/D5003.

This reduces the peak memory usage of Haddock on the `ghc` library back down to ~1GB from > 2GB before. It basically fixes the memory regression in deddced31cabadf62fe01fff77b094cd005e52a1 (see [this comment for graphs](https://github.com/haskell/haddock/issues/462#issuecomment-406077792)). Here is what the new graph looks like:

screen shot 2018-07-23 at 2 00 25 pm

**Comment by alexbiehl** [comment]
Now we have both! Precise instances and more efficient memory usage!

**Comment by harpocrates** [comment]
Ping? Is there no hope of this making it into 8.6?

**Comment by alexbiehl** [comment]
Hmmm. https://phabricator.haskell.org/D5003 hasn't been merged yet. Ping @bgamari

**Comment by bgamari** [comment]
@alexbiehl in general I can't merge this sort of thing until the Haddock patch has merged. Afterall, otherwise I can't bump the submodule.

**Pull request merged**
