### PR TITLE
Update CI's version of GHC to 9.2.1 release

### PR DESCRIPTION
**Pull request by ulysses4ever**

### CODE REVIEW

**Comment by ulysses4ever** [comment]
This is funny: tests are failing on CI while passing fine locally.

**Comment by andreasabel** [comment]
Are you also getting [this warning](https://github.com/haskell/haddock/runs/4277061277?check_suite_focus=true#step:8:56) locally?
```
Warning: Unknown/unsupported 'ghc' version detected 
(Cabal 3.2.1.0 supports 'ghc' version < 8.12)
```

**Comment by Kleidukos** [comment]
Alright, Bug25 seems to be a pain.

**Review by Kleidukos — APPROVED** [review]
Approval despite broken CI

**Comment by ulysses4ever** [comment]
@andreasabel yes, I saw it. Wasn't sure where it comes from, and it didn't hurt the tests.

> Approval despite broken CI

Sigh... I hoped to get CI back to green :'-(

**Comment by Kleidukos** [comment]
It's not you, it's us.

**Comment by Bodigrim** [comment]
As a Hackage trustee, I revised `haddock-library-1.10` to allow build with GHC 9.2: https://hackage.haskell.org/package/haddock-library-1.10.0/revisions/

**Pull request merged**
