### PR TITLE
Fix hyperlinker crash when there are no SrcSpans in the file due to CPP

### LINKED ISSUE #1091: Haddock 2.23.0 regression: --hyperlinked-source breaks vault-0.3.1.3
The [`vault-0.3.1.3`](http://hackage.haskell.org/package/vault-0.3.1.3) library no longer works with `stack haddock` on a GHC 8.8.1-based resolver (such as [this one](https://www.stackage.org/nightly-2019-09-27)). After some digging, I discovered that the culprit is `stack haddock`'s use of the `--hyperlinked-source` flag. To reproduce the issue, pick one of the following options (depending on your favorite build tool):

* `stack`

  <details>

  ```
  $ stack unpack vault-0.3.1.3 && cd vault-0.3.1.3
  Unpacked vault (from Hackage) to /home/rgscott/Documents/Hacking/Haskell/vault-0.3.1.3/

  $ stack --resolver nightly-2019-09-27 init
  Looking for .cabal or package.yaml files to use to init the project.
  Using cabal packages:
  - ./
  
  Selected resolver: nightly-2019-09-27
  Initialising configuration using resolver: nightly-2019-09-27
  Total number of user packages considered: 1
  Writing configuration to file: stack.yaml
  All done.

  $ stack haddock
  Stack has not been tested with GHC versions above 8.6, and using 8.8.1, this may fail
  Stack has not been tested with Cabal versions above 2.4, but version 3.0.0.0 was found, this may fail
  vault> configure (lib)
  Configuring vault-0.3.1.3...
  vault> build (lib)
  Preprocessing library for vault-0.3.1.3..
  Building library for vault-0.3.1.3..
  [1 of 5] Compiling Data.Unique.Really
  
  /home/rgscott/Documents/Hacking/Haskell/vault-0.3.1.3/src/Data/Unique/Really.hs:6:1: warning: [-Wunused-imports]
      The import of ‘Control.Applicative’ is redundant
        except perhaps to import instances from ‘Control.Applicative’
      To import instances alone, use: import Control.Applicative()
    |
  6 | import Control.Applicative ((<$>))
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [2 of 5] Compiling Data.Vault.ST.Lazy
  
  /home/rgscott/Documents/Hacking/Haskell/vault-0.3.1.3/src/Data/Vault/ST/ST.h:15:1: warning: [-Wunused-imports]
      The import of ‘Data.Monoid’ is redundant
        except perhaps to import instances from ‘Data.Monoid’
      To import instances alone, use: import Data.Monoid()
     |
  15 | import Data.Monoid (Monoid(..))
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  
  /home/rgscott/Documents/Hacking/Haskell/vault-0.3.1.3/src/Data/Vault/ST/ST.h:16:1: warning: [-Wunused-imports]
      The import of ‘Data.Semigroup’ is redundant
        except perhaps to import instances from ‘Data.Semigroup’
      To import instances alone, use: import Data.Semigroup()
     |
  16 | import Data.Semigroup (Semigroup((<>)))
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  
  /home/rgscott/Documents/Hacking/Haskell/vault-0.3.1.3/src/Data/Vault/ST/ST.h:18:1: warning: [-Wunused-imports]
      The import of ‘Control.Applicative’ is redundant
        except perhaps to import instances from ‘Control.Applicative’
      To import instances alone, use: import Control.Applicative()
     |
  18 | import Control.Applicative ((<$>))
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [3 of 5] Compiling Data.Vault.Lazy
  [4 of 5] Compiling Data.Vault.ST.Strict
  
  /home/rgscott/Documents/Hacking/Haskell/vault-0.3.1.3/src/Data/Vault/ST/ST.h:15:1: warning: [-Wunused-imports]
      The import of ‘Data.Monoid’ is redundant
        except perhaps to import instances from ‘Data.Monoid’
      To import instances alone, use: import Data.Monoid()
     |
  15 | import Data.Monoid (Monoid(..))
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  
  /home/rgscott/Documents/Hacking/Haskell/vault-0.3.1.3/src/Data/Vault/ST/ST.h:16:1: warning: [-Wunused-imports]
      The import of ‘Data.Semigroup’ is redundant
        except perhaps to import instances from ‘Data.Semigroup’
      To import instances alone, use: import Data.Semigroup()
     |
  16 | import Data.Semigroup (Semigroup((<>)))
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  
  /home/rgscott/Documents/Hacking/Haskell/vault-0.3.1.3/src/Data/Vault/ST/ST.h:18:1: warning: [-Wunused-imports]
      The import of ‘Control.Applicative’ is redundant
        except perhaps to import instances from ‘Control.Applicative’
      To import instances alone, use: import Control.Applicative()
     |
  18 | import Control.Applicative ((<$>))
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [5 of 5] Compiling Data.Vault.Strict
  
  vault> haddock
  Preprocessing library for vault-0.3.1.3..
  Running Haddock on library for vault-0.3.1.3..
  
  src/Data/Unique/Really.hs:6:1: warning: [-Wunused-imports]
      The import of ‘Control.Applicative’ is redundant
        except perhaps to import instances from ‘Control.Applicative’
      To import instances alone, use: import Control.Applicative()
    |
  6 | import Control.Applicative ((<$>))
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  
  src/Data/Vault/ST/ST.h:15:1: warning: [-Wunused-imports]
      The import of ‘Data.Monoid’ is redundant
        except perhaps to import instances from ‘Data.Monoid’
      To import instances alone, use: import Data.Monoid()
     |
  15 | import Data.Monoid (Monoid(..))
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  
  src/Data/Vault/ST/ST.h:16:1: warning: [-Wunused-imports]
      The import of ‘Data.Semigroup’ is redundant
        except perhaps to import instances from ‘Data.Semigroup’
      To import instances alone, use: import Data.Semigroup()
     |
  16 | import Data.Semigroup (Semigroup((<>)))
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  
  src/Data/Vault/ST/ST.h:18:1: warning: [-Wunused-imports]
      The import of ‘Control.Applicative’ is redundant
        except perhaps to import instances from ‘Control.Applicative’
      To import instances alone, use: import Control.Applicative()
     |
  18 | import Control.Applicative ((<$>))
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  
  src/Data/Vault/ST/ST.h:15:1: warning: [-Wunused-imports]
      The import of ‘Data.Monoid’ is redundant
        except perhaps to import instances from ‘Data.Monoid’
      To import instances alone, use: import Data.Monoid()
     |
  15 | import Data.Monoid (Monoid(..))
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  
  src/Data/Vault/ST/ST.h:16:1: warning: [-Wunused-imports]
      The import of ‘Data.Semigroup’ is redundant
        except perhaps to import instances from ‘Data.Semigroup’
      To import instances alone, use: import Data.Semigroup()
     |
  16 | import Data.Semigroup (Semigroup((<>)))
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  
  src/Data/Vault/ST/ST.h:18:1: warning: [-Wunused-imports]
      The import of ‘Control.Applicative’ is redundant
        except perhaps to import instances from ‘Control.Applicative’
      To import instances alone, use: import Control.Applicative()
     |
  18 | import Control.Applicative ((<$>))
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  Haddock coverage:
   100% (  4 /  4) in 'Data.Unique.Really'
    80% ( 12 / 15) in 'Data.Vault.ST.Lazy'
    Missing documentation for:
      Vault (src/Data/Vault/ST/backends/GHC.h:18)
      Key (src/Data/Vault/ST/backends/GHC.h:19)
      Locker (src/Data/Vault/ST/backends/GHC.h:40)
   100% ( 15 / 15) in 'Data.Vault.Lazy'
    80% ( 12 / 15) in 'Data.Vault.ST.Strict'
    Missing documentation for:
      Vault (src/Data/Vault/ST/backends/GHC.h:18)
      Key (src/Data/Vault/ST/backends/GHC.h:19)
      Locker (src/Data/Vault/ST/backends/GHC.h:40)
   100% ( 15 / 15) in 'Data.Vault.Strict'
  haddock: internal error: couldn't find ast for src/Data/Vault/ST/Lazy.hs ["src/Data/Vault/ST/ST.h","src/Data/Vault/ST/backends/GHC.h"]
  CallStack (from HasCallStack):
    error, called at utils/haddock/haddock-api/src/Haddock/Backends/Hyperlinker.hs:78:28 in main:Haddock.Backends.Hyperlinker
  
  --  While building package vault-0.3.1.3 using:
        /home/rgscott/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_3.0.0.0_ghc-8.8.1 --builddir=.stack-work/dist/x86_64-linux/Cabal-3.0.0.0 haddock --html --hoogle --html-location=../$pkg-$version/ --haddock-option=--hyperlinked-source --haddock-option=--quickjump
      Process exited with code: ExitFailure 1
  ```
  </details>
* `cabal`

  <details>
  
  ```
  $ cabal get vault-0.3.1.3 && cd vault-0.3.1.3                                                      
  Unpacking to vault-0.3.1.3/

  $ /opt/ghc/8.8.1/bin/haddock --version
  Haddock version 2.23.0, (c) Simon Marlow 2006
  Ported to use the GHC API by David Waern 2006-2008

  $ cabal haddock -w /opt/ghc/8.8.1/bin/ghc --haddock-option=--hyperlinked-source
  Resolving dependencies...
  Build profile: -w ghc-8.8.1 -O1
  In order, the following will be built (use -v for more details):
   - vault-0.3.1.3 (first run)
  Configuring vault-0.3.1.3...
  Preprocessing library for vault-0.3.1.3..
  Running Haddock on library for vault-0.3.1.3..
  Warning: The documentation for the following packages are not installed. No
  links will be generated to these packages: hashable-1.3.0.0,
  semigroups-0.19.1, unordered-containers-0.2.10.0
  Haddock coverage:
  
  src/Data/Unique/Really.hs:6:1: warning: [-Wunused-imports]
      The import of ‘Control.Applicative’ is redundant
        except perhaps to import instances from ‘Control.Applicative’
      To import instances alone, use: import Control.Applicative()
    |
  6 | import Control.Applicative ((<$>))
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   100% (  4 /  4) in 'Data.Unique.Really'
  
  src/Data/Vault/ST/ST.h:15:1: warning: [-Wunused-imports]
      The import of ‘Data.Monoid’ is redundant
        except perhaps to import instances from ‘Data.Monoid’
      To import instances alone, use: import Data.Monoid()
     |
  15 | import Data.Monoid (Monoid(..))
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  
  src/Data/Vault/ST/ST.h:16:1: warning: [-Wunused-imports]
      The import of ‘Data.Semigroup’ is redundant
        except perhaps to import instances from ‘Data.Semigroup’
      To import instances alone, use: import Data.Semigroup()
     |
  16 | import Data.Semigroup (Semigroup((<>)))
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  
  src/Data/Vault/ST/ST.h:18:1: warning: [-Wunused-imports]
      The import of ‘Control.Applicative’ is redundant
        except perhaps to import instances from ‘Control.Applicative’
      To import instances alone, use: import Control.Applicative()
     |
  18 | import Control.Applicative ((<$>))
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    80% ( 12 / 15) in 'Data.Vault.ST.Lazy'
    Missing documentation for:
      Vault (src/Data/Vault/ST/backends/GHC.h:18)
      Key (src/Data/Vault/ST/backends/GHC.h:19)
      Locker (src/Data/Vault/ST/backends/GHC.h:40)
   100% ( 15 / 15) in 'Data.Vault.Lazy'
  
  src/Data/Vault/ST/ST.h:15:1: warning: [-Wunused-imports]
      The import of ‘Data.Monoid’ is redundant
        except perhaps to import instances from ‘Data.Monoid’
      To import instances alone, use: import Data.Monoid()
     |
  15 | import Data.Monoid (Monoid(..))
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  
  src/Data/Vault/ST/ST.h:16:1: warning: [-Wunused-imports]
      The import of ‘Data.Semigroup’ is redundant
        except perhaps to import instances from ‘Data.Semigroup’
      To import instances alone, use: import Data.Semigroup()
     |
  16 | import Data.Semigroup (Semigroup((<>)))
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  
  src/Data/Vault/ST/ST.h:18:1: warning: [-Wunused-imports]
      The import of ‘Control.Applicative’ is redundant
        except perhaps to import instances from ‘Control.Applicative’
      To import instances alone, use: import Control.Applicative()
     |
  18 | import Control.Applicative ((<$>))
     | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    80% ( 12 / 15) in 'Data.Vault.ST.Strict'
    Missing documentation for:
      Vault (src/Data/Vault/ST/backends/GHC.h:18)
      Key (src/Data/Vault/ST/backends/GHC.h:19)
      Locker (src/Data/Vault/ST/backends/GHC.h:40)
   100% ( 15 / 15) in 'Data.Vault.Strict'
  Warning: Data.Unique.Really: could not find link destinations for:
      Hashable hashWithSalt hash
  haddock: internal error: couldn't find ast for src/Data/Vault/ST/Lazy.hs ["src/Data/Vault/ST/ST.h","src/Data/Vault/ST/backends/GHC.h"]
  CallStack (from HasCallStack):
    error, called at utils/haddock/haddock-api/src/Haddock/Backends/Hyperlinker.hs:78:28 in main:Haddock.Backends.Hyperlinker
  cabal: Failed to build documentation for vault-0.3.1.3.
  ```
  </details>

This is a regression from Haddock 2.22.0, which does not error:

<details>

```
$ /opt/ghc/8.6.5/bin/haddock --version
Haddock version 2.22.0, (c) Simon Marlow 2006
Ported to use the GHC API by David Waern 2006-2008

$ cabal haddock -w /opt/ghc/8.6.5/bin/ghc --haddock-option=--hyperlinked-source
Resolving dependencies...
Build profile: -w ghc-8.6.5 -O1
In order, the following will be built (use -v for more details):
 - vault-0.3.1.3 (first run)
Configuring vault-0.3.1.3...
Preprocessing library for vault-0.3.1.3..
Running Haddock on library for vault-0.3.1.3..
Warning: The documentation for the following packages are not installed. No
links will be generated to these packages: hashable-1.3.0.0,
semigroups-0.19.1, unordered-containers-0.2.10.0
Haddock coverage:
 100% (  4 /  4) in 'Data.Unique.Really'
  80% ( 12 / 15) in 'Data.Vault.ST.Lazy'
  Missing documentation for:
    Vault (src/Data/Vault/ST/backends/GHC.h:18)
    Key (src/Data/Vault/ST/backends/GHC.h:19)
    Locker (src/Data/Vault/ST/backends/GHC.h:40)
 100% ( 15 / 15) in 'Data.Vault.Lazy'
  80% ( 12 / 15) in 'Data.Vault.ST.Strict'
  Missing documentation for:
    Vault (src/Data/Vault/ST/backends/GHC.h:18)
    Key (src/Data/Vault/ST/backends/GHC.h:19)
    Locker (src/Data/Vault/ST/backends/GHC.h:40)
 100% ( 15 / 15) in 'Data.Vault.Strict'
Warning: Data.Unique.Really: could not find link destinations for:
    Hashable hashWithSalt hash
Documentation created:
/home/rgscott/Documents/Hacking/Haskell/vault-0.3.1.3/dist-newstyle/build/x86_64-linux/ghc-8.6.5/vault-0.3.1.3/doc/html/vault/index.html
```
</details>

I'll try to come up with a more minimal test case shortly.

### PR DESCRIPTION
**Pull request by wz1000**
This eliminates a call to `error` which gets hit in situations when the `.hie` file doesn't contain any `SrcSpan`s from the file we are actually hyperlinking. This can occur when the file is wholly composed of CPP `#include`s.

Fixes #1091

### CODE REVIEW

**Comment by RyanGlScott** [comment]
Thanks! I can confirm that this allows me to build the Haddocks for `vault` once more.

**Comment by RyanGlScott** [comment]
Thanks, @harpocrates!

This is probably a long shot, but I don't suppose there's any way to make this fix available in a future version of Haddock to be bundled with a GHC 8.8 point release? I'm not aware of a workaround for the underlying issue, which makes it rather annoying to deal with.

**Comment by harpocrates** [comment]
@RyanGlScott I agree that this is pretty nasty bug. I'll open up a MR to bump the Haddock submodule on GHC's 8.8 branch. Maybe Ben will allow it... I seem to recall some thing like this happening before, although it was probably back when the release cadence was much slower.

Do you know what the state is of GHC's head.hackage testing? Maybe `haddock`-ing could become part of that testsuite to catch this sort of breakage before releasing. Evidently the bootlibs are not enough, since that's what I'd been using.

**Comment by RyanGlScott** [comment]
> Do you know what the state is of GHC's head.hackage testing?

The `head.hackage` repo does have proper CI now, although it's unclear to me whether running Haddock is a part of this CI (perhaps @bgamari could answer this question). Even if it does run Haddocks, I'm not sure if it specifically enables the `--hyperlinked-source` flag. I myself didn't notice this because `cabal haddock` (which is my usual tool of the trade) doesn't enable `--hyperlinked-source` by default—it's only when I tried out `stack haddock` one day where I _did_ notice it, since that does use `--hyperlinked-source` by default.

**Comment by harpocrates** [comment]
@bgamari Would it be possible to bump the Haddock submodule again for 8.8.2? This bug is pretty nasty. If it is possible, I'll make the version changes and open a MR.

**Pull request merged**
