### PR TITLE
Clear search string on quickjump hide for #781

### PR DESCRIPTION
**Pull request by jhenahan**
Not sure if it's too aggressive to reset the search string every time the quickjump is hidden, so I'm happy to change it if it's too much.

### CODE REVIEW

**Comment by alexbiehl** [comment]
Thank you @jhenahan, looks good to me! @merijn you opened the issue, do you have an opinion about this?

**Comment by alexbiehl** [comment]
Jack, maybe https://github.com/haskell/haddock/issues/783 is also interesting for you? It will involve a small haskell patch this time.

**Comment by merijn** [comment]
Looks sensible enough to me.

**Comment by jhenahan** [comment]
@alexbiehl I was looking into that one, as well. I have a couple of ideas about it, so I’ll try to get a patch together if no one beats me to it. :)

**Comment by alexbiehl** [comment]
Nice, looking forward to it! Merging this one for now.

**Pull request merged**
