### PR TITLE
Add UnitId to Target record

### PR DESCRIPTION
**Pull request by fendor**
Companion to https://gitlab.haskell.org/ghc/ghc/-/merge_requests/4937#note_328434

### CODE REVIEW

**Comment by alexbiehl** [comment]
🚢 Fire away sir! Please note that there are multiple PRs with haddock changes around, really only merge once the corresponding Ghc MR goes in to avoid a jam.

**Comment by Ericson2314** [comment]
#1310 thread explains why this is two commits.

**Comment by fendor** [comment]
So, can we merge this now or is there more to it?

**Comment by Ericson2314** [comment]
Yeah, let's mereg now that that GHC MR is passing.

**Comment by Kleidukos** [comment]
Great, let's go then!

**Comment by Ericson2314** [comment]
Thanks!

**Comment by hsyl20** [comment]
This has been reverted in 50100be46ce636a04957506144a8a18531e82506...

**Comment by Ericson2314** [comment]
Thanks for the heads up. Looks like https://gitlab.haskell.org/ghc/ghc/-/merge_requests/5092 is almost merged, then we could have another go perhaps.

**Comment by Ericson2314** [comment]
(though waiting until after 9.2 if there are other bumps might be prudent.)

**Pull request merged**
