### PR TITLE
Add support for labeled module references

### PR DESCRIPTION
**Pull request by garetxe**
Support a markdown-style way of annotating module references. For instance

-- | [label]("Module.Name#anchor")

will create a link that points to the same place as the module
reference "Module.Name#anchor" but the text displayed on the link will
be "label".

(This is a rebase of https://github.com/haskell/haddock/pull/1181 for ghc-9.0, as requested in https://github.com/haskell/haddock/pull/1181#issuecomment-774491769)

### CODE REVIEW

**Comment by garetxe** [comment]
Just to clarify: this was already merged in the `ghc-8.10` branch, but was not brought forward to `ghc-9.0`. I rebased so it is easier to merge in `ghc-9.0`, as @Kleidukos suggested.

**Comment by Kleidukos** [comment]
@garetxe Any idea why we're hitting https://github.com/haskell/haddock/pull/1315/checks?check_run_id=1845591424#step:7:65 ?

**Comment by garetxe** [comment]
Yes, this should be fixed by https://github.com/haskell/haddock/pull/1315/commits/0fd913106014ecf27bdc3c8fa3e6528b8c86dc3e : the `DocModule` constructor now takes a `ModLink` argument, and not a plain `String`. The error was due to `OverloadedStrings` trying to make sense out of this.

**Comment by Kleidukos** [comment]
Alright now we're hitting 

```
2021-02-06T20:55:25.2278472Z hoogle-test: hoogle-test/out/Bug873: removeDirectoryRecursive:getSymbolicLinkStatus: does not exist (No such file or directory)
2021-02-06T20:55:25.2280079Z Failed to run Haddock on test package 'Bug873'
```

**Comment by garetxe** [comment]
There is still a failing test, but this is the same Bug873 as last time, due to the change on the interface version (see comments https://github.com/haskell/haddock/pull/1181#issuecomment-760984308 and https://github.com/haskell/haddock/pull/1296#discussion_r563339358). If I remove that test the tests pass locally for me.

Please let me know if you would like me to add a commit removing that test from my branch.

**Comment by Kleidukos** [comment]
@garetxe This is also the symptom of something deeper. I have a call with Alex tomorrow and we'll decide of a solution. Otherwise, it's all good. I'll merge the PR when it's all green. :)

**Comment by garetxe** [comment]
OK, great, thanks a lot :)

**Comment by Kleidukos** [comment]
@garetxe Alright, I've had the call with @alexbiehl and we decided to make some changes to the PR to ensure backward compatibility. Another PR will be opened so that you're not bothered anymore. We shall put your name in the "Authored by" field in the commit. 
Thanks a lot! :sparkles:

**Comment by garetxe** [comment]
Great, thanks a lot! :)

**Comment by garetxe** [comment]
Oh, and I don't care about the authorship part, as long as the patch goes in in some form I am happy!
So feel free to directly commit your changes.

**Pull request closed without merging**
