### PR TITLE
Check if doc-index.json exists before reading it

### PR DESCRIPTION
**Pull request by coot**

### CODE REVIEW

**Review by Kleidukos — APPROVED** [review]

**Comment by andreasabel** [comment]
@coot @Kleidukos : This fix is great, because `cabal haddock --enable-documentation` crashes under GHC 9.0/2 for me with an internal error, e.g.:
```
haddock: internal error: .cabal/store/ghc-9.2.3/rgx-bs-0.94.0.2-390080d4/share/doc/html/doc-index.json: openBinaryFile: does not exist (No such file or directory)
```
Would be great to have this soon!
Is there a release plan yet for this fix?  (I do not see a milestone attached to it...)

**Comment by Kleidukos** [comment]
@andreasabel hi, I believe the fix should be bundled with the next Haddock release that GHC will use, alongside with the Hi Haddock patch

**Comment by andreasabel** [comment]
Any hope of back-porting to GHC 9.2?  (In case they make another minor release.)

**Comment by Kleidukos** [comment]
I don't understand this question, the merge target was for GHC 9.2. You should ask the GHC developers

**Comment by ulysses4ever** [comment]
Right... There was a mention on ghc-devs of 9.2.4 scheduled for the "end of July". https://mail.haskell.org/pipermail/ghc-devs/2022-June/020773.html

**Pull request merged**
