### PR TITLE
Add support for custom section anchors

### PR DESCRIPTION
**Pull request by garetxe**
As discussed in https://github.com/haskell/haddock/issues/1164

### CODE REVIEW

**Comment by harpocrates** [comment]
Thank you putting this together, it looks great. Before merging, do you think you could add something about this in the Haddock manual around here: https://github.com/haskell/haddock/blob/ghc-8.10/doc/markup.rst#section-headings?

**Comment by garetxe** [comment]
Thanks for taking a look! I just added some documentation for this in ed6e7b2. I would be happy to change it if you think of a better way to document the change.

**Comment by garetxe** [comment]
Sorry, noticed a typo, should be better now.

**Comment by harpocrates** [comment]
Looks great, thank you for putting this all together. 👍

**Comment by garetxe** [comment]
Great, thanks a lot!

**Pull request merged**
