### PR TITLE
Fix HEAD html-test

### PR DESCRIPTION
**Pull request by harpocrates**
* `StarIsType` changes caused `html-test` to crash
 * `html-test` output was not taking into account tooltip changes (how is this even passing on CI?)

### CODE REVIEW

**Comment by alexbiehl** [comment]
ugh to crash? Thanks for paying this close attention Alec.

**Comment by harpocrates** [comment]
Although the `StarIsType` changes are probably not going to be needed for 8.6 (I'll revert the commit once the decision is official), the changes in 91b0f9221b273305b8cec68c011f35e1ff33aa18 are still necessary as of the alpha release (`ghc-8.6.0.20180627`).

I still don't understand how the accepted output in the `ghc-head` branch ever could have been produced.  It is probably an issue with the global package DB for whatever is on @hvr's GHC-HEAD PPA, since that is what was used both for accepting and for CI (which I recall was passing, despite the expected output looking wrong).

Tomorrow (hopefully?) I'll spin up an Ubuntu VM and try to replicate the buggy CI output.

**Comment by harpocrates** [comment]
> I still don't understand how the accepted output in the ghc-head branch ever could have been produced. It is probably an issue with the global package DB for whatever is on @hvr's GHC-HEAD PPA, since that is what was used both for accepting and for CI (which I recall was passing, despite the expected output looking wrong).
>
> Tomorrow (hopefully?) I'll spin up an Ubuntu VM and try to replicate the buggy CI output.

I've run out of ideas why the tests were passing on CI on `ghc-head` (before they got broken by the `StarIsType` changes).

Now that `StarIsType` changes have been reverted, all this PR does is accept the correct output.

**Comment by sjakobi** [comment]
I think that when accepting the `html-test` changes in #857, I may have gotten the `html-test` invocation wrong and used the default `haddock` version on my system.

Clearly that's my oversight, but the ergonomics around `html-test` could be a lot better too. I guess what I'm really missing is a `--test-arguments` flag for `cabal new-test`…

**Comment by sjakobi** [comment]
Also: LGTM!

**Pull request merged**
