### PR TITLE
Add HEAD.hackage overlay

### PR DESCRIPTION
**Pull request by harpocrates**
Latest attempt to get tests working on `ghc-head`.

### CODE REVIEW

**Comment by alexbiehl** [comment]
Nice timing

**Comment by alexbiehl** [comment]
Simon is playing around with that too at this moment.

**Comment by harpocrates** [comment]
There needs to be an IRC channel for haddock. 😄

**Comment by sjakobi** [comment]
Alec, I'm currently using Google hangout to chat with Alex and Herbert. Would you like to join?

**Comment by alexbiehl** [comment]
Actually, there is also IRC (but my bouncer broke and I couldn't get it to work for months now)

**Comment by sjakobi** [comment]
> Actually, there is also IRC (but my bouncer broke and I couldn't get it to work for months now)

You mean #haddock?

**Comment by harpocrates** [comment]
> Alec, I'm currently using Google hangout to chat with Alex and Herbert. Would you like to join?

Thanks for the the invite. If you're OK with it, that would be convenient.

**Comment by sjakobi** [comment]
> Thanks for the the invite. If you're OK with it, that would be convenient.

I've added you. Did you get a notification?

**Comment by harpocrates** [comment]
Nope, nothing yet.

**Comment by sjakobi** [comment]
I've started a new group. I've invited you using the email address listed on your GitHub profile.

**Comment by harpocrates** [comment]
I've opened https://github.com/hvr/head.hackage/pull/76 for the `primitive` build issue.

**Pull request merged**
