### PR TITLE
Logger refactoring

### PR DESCRIPTION
**Pull request by hsyl20**
Fix after https://gitlab.haskell.org/ghc/ghc/-/merge_requests/4757

### CODE REVIEW

**Review by alexbiehl — APPROVED** [review]
🚢

**Comment by hsyl20** [comment]
It seems like my MR includes an additional commit that is in GHC's submodule but not in `ghc-head` branch?

**Comment by alexbiehl** [comment]
Uh woot, is ghc pointing to the haddock repo on Gitlab? Sounds like we are out of sync then.

**Comment by Ericson2314** [comment]
I think @adinapoli pushed a non-`wip/` branch over there with WIP intent

**Comment by hsyl20** [comment]
@Ericson2314 I don't think so: https://gitlab.haskell.org/ghc/ghc/-/commit/b1a17507229b00820b9552a423342f8c354267d4 (merged in master) bumped haddock on purpose. It's just ghc-head that is not up to date. for some reason

**Comment by Ericson2314** [comment]
@hsyl20 err I don't mean the commit wasn't ready, but just that I think it was meant for that commit to already be in `ghc-head`. (The process of using `wip/*` branch names for things that are no longer a work in progress, especially when we merge not rebase as we do with Hackage, then a bit confusing.)

**Comment by adinapoli** [comment]
Oops -- did I screw something up here? I am relatively new to contributing to GHC and admittedly adding things to a git submodules confuses me every-single-time 😉 

Was there anything extra I should have done, or is this part of normal reconciliation between Gitlab and Github?

**Comment by hsyl20** [comment]
@adinapoli It's just strange that you were allowed to create a "adinapoli/remove-errdoc" branch in GHC's haddock fork. I thought we were only allowed to create "wip/" prefixed branches in this repository, but maybe not. Anyway it explains why the submodule linter thought your commit was merged upstream.

The usual submodule process is to:
1. push a "wip/whatever" branch in GHC's haddock while developing your MR. "wip/" branches for submodules are allowed by the linter in merge requests except in Marge's one (so a green MR for you may become red when Marge tries to merge it...)
2. when your branch is ready to be merged, open a PR for your "wip/whatever" branch here upstream against `ghc-head` branch
3. when it's merged, if the commit hash has changed for some reason (additional merge commit, another commit that went in in between, etc.), fix your MR to use this new commit
4. finally assign to Marge and pray :)

Dura processus sed processus ;)

**Comment by adinapoli** [comment]
> It's just strange that you were allowed to create a "adinapoli/remove-errdoc" branch in GHC's haddock fork.

Ah,sorry, I think that was just a bona-fide oversight. When starting to work on GHC's [#18516](https://gitlab.haskell.org/ghc/ghc/-/issues/18516) I was puzzled on how I was supposed to make changes to the Haddock submodule as I couldn't push into _any_ branch, and @mpickering gave me access to the repo, I guess in a too-broad granularity. TIL, I wasn't aware of the "wip/non-wip" rule 😉 

> Dura processus sed processus ;)

Ops! I had no idea the process was so articulated even for submodules. Noted! I will make sure I abide to the process for the next MRs.

**Comment by alexbiehl** [comment]
There you go 🚢

**Comment by hsyl20** [comment]
Thanks! Sadly GHC's mirror is broken :sob: 

screenshot-20210208@184730

https://gitlab.haskell.org/ghc/haddock/-/branches/active

**Pull request merged**
