### PR TITLE
Accept haddockHtmlTest test output for ghc-9.0

### PR DESCRIPTION
**Pull request by monoidal**
Refs #1350

### CODE REVIEW

**Comment by Kleidukos** [comment]
Looks like this diff is not valid for the ghc-9.0 branch, @monoidal

**Comment by Kleidukos** [comment]
@monoidal Should I close this PR? Do you intend to keep working on it?

**Comment by monoidal** [comment]
I'm currently busy but will go back to it.

**Comment by Kleidukos** [comment]
@monoidal gentle ping. :)

**Comment by monoidal** [comment]
At the moment, CI on the `ghc-9.0` branch in GHC gitlab is broken, I will get back to this once it's fixed. https://gitlab.haskell.org/ghc/ghc/-/merge_requests/6336#note_370676

**Comment by Kleidukos** [comment]
@mergifyio rebase

**Comment by monoidal** [comment]
Since 9.4 was released and this MR is only about a different expected output, I'm closing as abandoned/no longer relevant.

**Pull request closed without merging**
