### PR TITLE
Hide instances by default (#698)

### LINKED ISSUE #698: Hide instances by default
Even browsing through the Prelude is a hassle, among many other examples, because of the hundreds of instances that come with each type class.

### PR DESCRIPTION
**Pull request by Lysxia**
Fixes #698.

### CODE REVIEW

**Comment by alexbiehl** [comment]
I think this makes class heavy modules easier to browse, thank you. As in the other PR yoi need to update the tests.

**Comment by Lysxia** [comment]
Is there a command to update the tests?

**Comment by alexbiehl** [comment]
Yes, you can use the accept flag: `html-test -a` should do the trick!

**Comment by Lysxia** [comment]
Works like a charm.

**Comment by ntc2** [comment]
Is there anything holding this PR back? Really looking forward to this change!

**Comment by Lysxia** [comment]
Why was this closed?

**Comment by ntc2** [comment]
@Lysxia If you tried the EDIT button, and you looked for a "reopon" button when you add a comment, then I'm not sure. You could try adding another (pointless) commit to this PR, or create a new PR that references this one for context.

I don't have admin permissions on this repo, but perhaps someone who does could reopen it? But Googling a bit, I get the impression that GitHub is restrictive when it comes to reopening PRs, at least if they've been merged (not the case here). So if you can't reopen it, I doubt anyone else can.

**Comment by gbaz** [comment]
Indeed the reopen button is disabled with the message "the hide-instances branch was force-pushed or recreated". All the closed PRs will have to be rebased and resubmitted I think?

**Comment by Lysxia** [comment]
I might have been available if I didn't force push first. Reopened in #823.

**Pull request closed without merging**
