### PR TITLE
Issue 303

### PR DESCRIPTION
**Pull request by Helkafen**
Hide footer when printing.

### CODE REVIEW

**Comment by bgamari** [comment]
Out of curiosity: Why not simply add a CSS rule for `#footer` with the appropriate media type?

**Comment by bgamari** [comment]
e.g.,
```
@media print {
  #footer { display: none; }
}
```

This better matches with my intuitive understanding of how CSS is intended to be used:  separate document structure from presentation.

**Comment by Helkafen** [comment]
Your version is cleaner. I was thinking of reusing the noprint class someday, but I can't find any practical use right now.

**Comment by bgamari** [comment]
Looks good to me. However, could you be sure to squash the two commits into one with a proper commit message prior to merging?

**Comment by Helkafen** [comment]
Tried to, but github doesn't let me force push the squashed commit.

**Comment by hvr** [comment]
that's because you based thir pr off a branch in haskell/haddock which is protected against forcepushes... if you  create PRs from forked repos it would work....

**Comment by bgamari** [comment]
Herbert Valerio Riedel <notifications@github.com> writes:

> that's because you based thir pr off a branch in haskell/haddock which
> is protected against forcepushes... if you create PRs from forked
> repos it would work....
>
Indeed, in general I work in my own forks whenever possible; if nothing
else it minimizes the chance for mistakes (which I am quite prone to it seems).

**Comment by Helkafen** [comment]
Ok, I'll also work from my own fork then. Thanks for the explanation.

**Pull request closed without merging**
