### PR TITLE
Fix CI on `ghc-head`

### PR DESCRIPTION
**Pull request by harpocrates**
This unbreaks CI on `ghc-head`. The idea follows #859. There's a couple reasons for doing this:

  - We'll always be up to date on GHC changes. Worse case scenario, we wait a day and manually restart CI, but CI should _never_ be red for more than a day.
  - It'll be trivial to point to a custom GHC artifact, so Haddock branches which need custom GHC branches (like `wip/hi-haddock`) can continue to run CI

Making CI green also forced me to fix some breakage that's snuck in since stuff was last green.

### CODE REVIEW

**Comment by mpickering** [comment]
You could simplify the .travis script by using `language:nix` instead I think if that's a path you want to go down.

**Comment by harpocrates** [comment]
> You could simplify the .travis script by using `language:nix` instead I think if that's a path you want to go down.

Is there a polished way in Nix to install the validate artifacts and add the GHC HEAD overlay?  That sort of thing would be quite nice indeed.  Could you expand more on what you had in mind?

**Comment by mpickering** [comment]
I guess you would just want nix to install ghcHEAD and cabal but leave cabal to manage all haskell dependencies.

Setting up that environment can be managed in one command:

```
nix run -f https://github.com/mpickering/ghc-artefact-nix/archive/master.tar.gz ghcHEAD cabal-install
```

Perhaps you could also keep most of the current script the same and install the dependencies globally to save yourself mucking around unpacking them.

```
nix-env --dry-run -i -f https://github.com/mpickering/ghc-artefact-nix/archive/master.tar.gz ghcHEAD cabal-install
```

**Comment by harpocrates** [comment]
for the record: I would prefer some clean `nix` solution here (especially if it worked uniformly for GHC HEAD and non GHC HEAD), but there are other yaks to shave right now.

**Pull request merged**
