### PR TITLE
fix spelling errors

### PR DESCRIPTION
**Pull request by askeblad**
haddock-api/src/Haddock/Backends/Hyperlinker/Renderer.hs
haddock-api/src/Haddock/Backends/LaTeX.hs
haddock-api/src/Haddock/Backends/Xhtml/DocMarkup.hs
haddock-api/src/Haddock/Interface/Create.hs
haddock-api/src/Haddock/Types.hs
haddock-library/src/Documentation/Haddock/Parser.hs

@Kleidukos missed these in `#1464`

### CODE REVIEW

**Comment by askeblad** [comment]
got a MR open on GitLab linked to your ghc-tags issue

**Comment by Kleidukos** [comment]
@askeblad could you give me the link please?

**Comment by askeblad** [comment]
[!7937](https://gitlab.haskell.org/ghc/ghc/-/merge_requests/7937)

[#19884](https://gitlab.haskell.org/ghc/ghc/-/issues/19884)

**Comment by Kleidukos** [comment]
Thanks!

**Pull request merged**
