### PR TITLE
coot/multiple package (ghc-head)

### PR DESCRIPTION
**Pull request by coot**
The PRs #1277 and #1379 rebased onto ghc-head branch.

### CODE REVIEW

**Comment by coot** [comment]
I wasn't able to test it locally, because it does not build for me. I am getting various type errors due to changes in `ghc` package.

I am getting type errors due to changes in `ghc` package.

**Comment by Kleidukos** [comment]
@coot To test locally, you have to apply this patch to the haddock submodule in the GHC tree and run the tests. If you have issues with GHC master branch, please contact the GHC dev team. :)

**Comment by coot** [comment]
I mean, something a bit different.  To compile `exe:haddock` and verify that the changes works as intended. I wasn't able to build it with `ghc-head` (installed with `ghcup`, so quite like the `CI` does).

**Comment by Kleidukos** [comment]
@coot Can you uninstall ghc 9.2 and reinstall it like this?

```bash
$ ghcup install ghc -u "https://gitlab.haskell.org/api/v4/projects/1/jobs/artifacts/ghc-9.2/raw/ghc-x86_64-fedora27-linux.tar.xz?job=validate-x86_64-linux-fedora27" 9.2 
```

**Comment by coot** [comment]
With `ghc-9.2` I am getting:
```
cabal build -w ghc-9.2 exe:haddock
Warning: Unknown/unsupported 'ghc' version detected (Cabal 3.4.0.0 supports
'ghc' version < 9.1): /home/coot/.ghcup/bin/ghc-9.2 is version 9.2.0.20210805
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: haddock-api-2.24.0 (user goal)
[__1] next goal: ghc (dependency of haddock-api)
[__1] rejecting: ghc-9.2.0.20210805/installed-9.2.0.20210805 (conflict:
haddock-api => ghc^>=9.3)
```

I got slightly further with `ghc-head` (installed through ghcup):
```
cabal build --disable-documentation -w ghc-head --with-ghc-pkg ghc-pkg-head exe:haddock
Build profile: -w ghc-9.3.20210805 -O1
In order, the following will be built (use -v for more details):
 - haddock-api-2.24.0 (lib) (first run)
 - haddock-2.24.0 (exe:haddock) (first run)
Preprocessing library for haddock-api-2.24.0..
Building library for haddock-api-2.24.0..
[12 of 40] Compiling Haddock.GhcUtils ( src/Haddock/GhcUtils.hs, /home/coot/repos/ghc/utils/haddock/dist-newstyle/build/x86_64-linux/ghc-9.3.20210805/haddock-api-2.24.0/build/Had
dock/GhcUtils.o, /home/coot/repos/ghc/utils/haddock/dist-newstyle/build/x86_64-linux/ghc-9.3.20210805/haddock-api-2.24.0/build/Haddock/GhcUtils.dyn_o )

src/Haddock/GhcUtils.hs:184:61: error:
    • Couldn't match type ‘IsUnicodeSyntax’
                     with ‘GenLocated EpAnnCO (HsUniToken "->" "\8594")’
      Expected: LHsUniToken "->" "\8594" DocNameI
        Actual: IsUnicodeSyntax
    • In the first argument of ‘HsUnrestrictedArrow’, namely
        ‘NormalSyntax’
      In the second argument of ‘HsFunTy’, namely
        ‘(HsUnrestrictedArrow NormalSyntax)’
      In the first argument of ‘noLocA’, namely
        ‘(HsFunTy noAnn (HsUnrestrictedArrow NormalSyntax) a b)’
    |
184 |    mkFunTy a b = noLocA (HsFunTy noAnn (HsUnrestrictedArrow NormalSyntax) a b)
    |                                                             ^^^^^^^^^^^^
```

**Comment by coot** [comment]
@Kleidukos I rebased on a more recent version of `ghc-head`, and now I was able to verify that things work as expected.

**Comment by Kleidukos** [comment]
Thank you for your patience!

**Pull request merged**
