### PR TITLE
Clean up unused imports (rebase #1417)

### PR DESCRIPTION
**Pull request by ulysses4ever**
Target the right branch.

### CODE REVIEW

**Comment by ulysses4ever** [comment]
Rebase of #1417.

**Comment by Kleidukos** [comment]
@ulysses4ever Do you want to keep this one open? Or shall I close it?

**Comment by ulysses4ever** [comment]
I haven’t checked if it’s relevant anymore. If it isn’t or you think there’s another way to achieve it, feel free to close. If I can do something (e.g. rebase again), I could certainly do that.

**Comment by Kleidukos** [comment]
@ulysses4ever okay, a rebase would be welcome then. :)

**Comment by ulysses4ever** [comment]
@Kleidukos rebased.

**Comment by ulysses4ever** [comment]
Actually, it's not going to work anymore: one file in this PR doesn't have those imports on `ghc-9.2` anymore, and another doesn't build without those import. So, closing. Sorry for the noise.

**Comment by Kleidukos** [comment]
No worries :)

**Pull request closed without merging**
