### PR TITLE
Accept haddockHtmlTest test output for ghc-9.0

### PR DESCRIPTION
**Pull request by monoidal**
Refs #1350

### CODE REVIEW

**Review by Kleidukos — APPROVED** [review]
LGTM

**Comment by Kleidukos** [comment]
@monoidal Could you please rebase on top of current ghc-9.0? The CI is fixed with 62d763f

**Comment by monoidal** [comment]
@Kleidukos I don't have permission to forcepush.

**Comment by monoidal** [comment]
Reopening as #1355.

**Pull request closed without merging**
