### PR TITLE
Tests run on inplace GHC

### PR DESCRIPTION
**Pull request by harpocrates**
This makes it possible to actually run tests using an inplace GHC, fixing https://github.com/haskell/haddock/issues/850. I've also tested this on the `ghc-8.4` branch (by cherry-picking c7bc06743bcb9e88cd05edfae4b7269a8015adce) and the tests continued to pass as before.

I've noticed that inplace `ghc-pkg` is reporting some weird things...

  * `ghc-pkg --global field base haddock-html` never returns anything... even though that directory does exist if you build GHC with Haddocks enabled!

  * `ghc-pkg --global field base haddock-interfaces` will always return a path to a `.haddock` file...   even though that file only exists if you build GHC with Haddocks enabled!

### CODE REVIEW

**Comment by harpocrates** [comment]
> html-test and hoogle-test still fail for me, but for apparently different reasons now.

By failing, you mean running but not passing, right? If so, that is expected: several things have been committed to `ghc-head` without the expected test output having been updated.

**Comment by sjakobi** [comment]
>> html-test and hoogle-test still fail for me, but for apparently different reasons now.
> 
> By failing, you mean running but not passing, right? If so, that is expected: several things have been committed to ghc-head without the expected test output having been updated.

Right. Initially I had an issue with my local ghc build that made html-test fail. Now that I've fixed that, I'm getting the usual html diffs. :)

**Comment by alexbiehl** [comment]
Let's merge I guess?

**Comment by harpocrates** [comment]
What do you want to do about the fact that `ghc-tests` fail? Should I accept?

**Comment by alexbiehl** [comment]
Thanks!

**Pull request merged**
