### PR TITLE
WIP: Better identifier parsing

### LINKED ISSUE #951: The identifier parser should accept parenthesized operators like (+)
The identifier parser doesn't accept `'(+)'` as a reference to `+`, and instead requires `@('+')@` which is very unreadable IMHO.

### PR DESCRIPTION
**Pull request by harpocrates**
* `'(<|>)'` and ``` '`elem`' ``` now get parsed and rendered properly as links
  * `'DbModule'/'DbUnitId'` now properly get split apart into two links
  * some more small niceties...

The identifier parsing code is more precise and more efficient (although to be
fair: it is also longer and in its own module). On the rendering side, we need
to pipe through information about backticks/parens/unadorned all the way through
from renaming to the backends.

In terms of impact: a total of 35 modules in the entirety of the bootlib + ghc
lib docs change. The only "regression" is things like `'\0'`. These should be
changed to `@\\0@` (the path by which this previously worked seems accidental).

Fixes #951.

### TODO:

 - [ ] fix warnings, orphans instances
 - [ ] add fixture tests
 - [ ] amend manual and docs
 - [ ] bump Haddock interface version
 - [ ] accept test output

### CODE REVIEW

**Comment by harpocrates** [comment]
Examples of things that currently render badly or suboptimally and would be fixed with this:

### Synthetic:
  * ``` @x '(Prelude.++)' y@ ```
  * ``` @x '`Data.List.elem`' y@ ```
  * ``` 'ReallyMagical’PathologicalModule#.Int#’ ```
  * ``` 'ReallyMagical’PathologicalModule#.+#' ```
  * ``` ``somethingInfix`` ```
  * ``` 'foo''' ```

### Real life:

  * ``` ...type-class for the types which can be converted into 'DbModule'/'DbUnitId’. ```
  * ``` 'Data.Function.on', for instance @'sortBy' (‘Prelude.compare' ``Data.Function.on`` 'Prelude.fst')@. ```
  * ``` ... 'withSubstBndr'\/'withLiftedBndr’. ```
  * ``` '(<|>)' from the 'Alternative' class. ```

**Comment by alexbiehl** [comment]
(I think this is missing the `Identifier.hs` module)

**Comment by harpocrates** [comment]
> (I think this is missing the `Identifier.hs` module)

Right, that might be important! 😄

**Comment by harpocrates** [comment]
(Note to self: Haddock's CI will be of no help here since the `.haddock` files even from GHC HEAD can't match the changes we've just made. Right now, there is only one failing test, and I think I prefer the new output.)

**Comment by harpocrates** [comment]
Merged in a5199600c39d25d7b71dcb2328000c1c49ad95a2.

**Pull request closed without merging**
