### PR TITLE
Patch up the README file and add AppVeyor CI

### PR DESCRIPTION
**Pull request by harpocrates**

### CODE REVIEW

**Comment by harpocrates** [comment]
@hvr I'd like to add a Github webhook for Haddock to trigger the following build https://ci.appveyor.com/project/harpocrates/haddock (the webhook is https://ci.appveyor.com/api/github/webhook?id=u6nrftprb1ydueqq). AFAICT this is analogous to what Cabal does for their Appveyor script. Could you either give me the permissions to do this sort of thing to the repo or else do it yourself? Thanks!

**Comment by harpocrates** [comment]
@hvr ping ^^

**Comment by harpocrates** [comment]
@hvr ping ^^^

**Comment by simonmichael** [comment]
Should github actions be considered instead ? I've recently replaced travis and appveyor with it, for a nice overall simplification, and I could help.

Also from just now reviewing the status it appeared that @harpocrates is the current lead maintainer, and it's surprising to see that they don't have access to the repo settings. Could that be fixed ? I'd like to see haddock moving forward.

**Comment by harpocrates** [comment]
@simonmichael Github actions seems like a good idea. I've also had good experiences with it on other projects. I'll see if I have sufficient permissions to set it up.

**Comment by harpocrates** [comment]
@hvr ping ^^^^^

**Pull request closed without merging**
