### PR TITLE
html-test: Always set language

### PR DESCRIPTION
**Pull request by nomeata**
from ghc-9.2 on, the “default” langauge of GHC is expected to change
more wildly. To prepare for that (and unblock
https://gitlab.haskell.org/ghc/ghc/-/merge_requests/4853), this sets the
language for all the test files to `Haskell2010`. This should insolate
this test suite against changes to the default.

Cherry-picked from https://github.com/haskell/haddock/pull/1341

### CODE REVIEW

**Comment by nomeata** [comment]
This is the backport to `ghc-head`. I guess the reviewing and merging should first happen with https://github.com/haskell/haddock/pull/1341.

**Comment by nomeata** [comment]
Ah, #1341 was merged quickly. Do you want this to be merged like this, or do you merge `ghc-9.0` into `ghc-head` anyway manually, or how do you want to proceed, @Kleidukos

**Comment by Kleidukos** [comment]
@nomeata I'll take care of it, other PRs will be ported as well :)

**Comment by Kleidukos** [comment]
Change of plans, let's merge this one.

**Comment by Kleidukos** [comment]
@nomeata you should be good to go with the haddock submodule now. :)

**Pull request merged**
